INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #1', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2017-05-13', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #2', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-02-09', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #3', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2013-10-01', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #4', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2011-03-06', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #5', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2017-09-07', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #6', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2013-12-31', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #7', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2013-04-06', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #8', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2011-11-10', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #9', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-01-29', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #10', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-09-11', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #11', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2017-04-30', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #12', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2016-05-03', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #13', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-03-23', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #14', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2016-02-15', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #15', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2013-10-24', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #16', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2017-04-15', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #17', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2013-04-06', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #18', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2012-09-01', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #19', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2019-04-10', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #20', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-11-29', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #21', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-11-19', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #22', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-10-03', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #23', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2016-10-10', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #24', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2015-01-18', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #25', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2020-02-01', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #26', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2020-02-16', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #27', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2016-10-28', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #28', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2018-11-18', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #29', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2011-03-31', NOW());
INSERT INTO `research` (id, title, content, thumbnail, publication_date, created_at) VALUES (0, 'Project #30', '<p class="research__content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis tempor velit, in suscipit sapien convallis ac. Pellentesque est risus, pharetra at tortor ac, gravida accumsan risus. Phasellus ipsum enim, rutrum at scelerisque id, semper eleifend ex. Nam in purus a justo elementum pretium. Vestibulum ultricies, erat at dictum ullamcorper, turpis lorem iaculis mi, vel vehicula est lectus eleifend lorem. Suspendisse potenti. In quis orci non lorem auctor suscipit. Aliquam vitae nunc lacus. Maecenas in suscipit odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>', 'research/no-thumbnail.png','2017-08-05', NOW());







INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 1,'Stephanie', 'Strickland',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 1,'Michael', 'Wells',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 2,'Chad', 'Garcia',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 2,'Jessica', 'Moore',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 3,'Anna', 'Johnson',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 3,'Thomas', 'Daniel',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 4,'William', 'Soto',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 4,'Paula', 'Wilkinson',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 5,'Matthew', 'Owen',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 5,'Yvonne', 'Shaw',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 6,'Johnathan', 'Brown',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 6,'Michelle', 'Alvarez',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 7,'Jessica', 'Park',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 7,'Ronald', 'West',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 8,'Joseph', 'Morrison',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 8,'Krista', 'Sullivan',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 9,'Frank', 'Harrington',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 9,'Lisa', 'Frazier',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 10,'Debra', 'Lee',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 10,'Richard', 'Deleon',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 11,'Mariah', 'Brown',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 11,'Anna', 'Greene',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 12,'Lisa', 'Arias',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 12,'Jose', 'Brown',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 13,'Cynthia', 'Stephenson',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 13,'Barbara', 'Jones',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 14,'Tasha', 'Marshall',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 14,'Claire', 'Watkins',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 15,'Kristy', 'Collier',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 15,'Nicholas', 'Mitchell',  NOW());
INSERT INTO `author` (id, research_id, first_name, last_name, created_at) VALUES (0, 16,'Patrick', 'Peterson',  NOW());




